### ISSUE TITLE
How to acces the GhPost-GPS admin portal

### ISSUE THREAD

**Issue by aberba** [omnilesolutions/ghanapostgps#1]
Does https://gpsadmin.ghanapostgps.com/ require special access as part of a payed service? I'm interested in using their API.

**Comment by brightantwiboasiako** [comment]
Hi @aberba 
Yes you need to create an account. You can start by contacting https://www.vokacom.net/

**Comment by brightantwiboasiako** [comment]
I'm closing this issue as it's not specific to the project.
