### ISSUE TITLE
Why do i have to get asaase user id 

### ISSUE THREAD

**Issue by spiritkiddie** [omnilesolutions/ghanapostgps#2]
$asaaseUser = 'YOUR-ASAASE-USER-ID'
$deviceId = 'YOUR-DEVICE-ID'
$aesKey = 'YOUR-AES-KEY-FOR-DEVICE'

why the above variables needed to access the ghana post api?
is it free or one has to buy? if ghana post gps is free why sellling this api access.
how do i get this user id's?

**Comment by brightantwiboasiako** [comment]
You’ll need to have those credentials to access the Ghana post gps platform. You can contact the developers (Vokacom Ghana) for credentials. Please note however that it unfortunately takes more time than is necessary.

**Comment by spiritkiddie** [comment]
thanks this is very helpful....
